-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtSYG/55uNvky0Pz+
6B7HZ7QUPP2wnyTnLDRhz0VvYregCgYIKoZIzj0DAQehRANCAASzp6HJ6q+Hvkbn
obqQTMQCtHs8moGf/61i6ifEqATQJVzLil/8O2mmPnSddrL+FZO/HALhuhKyDziN
dhJccWjK
-----END PRIVATE KEY-----